### ISSUE TITLE
It literally doesn't work...

### ISSUE THREAD

**Issue by titoworlddev** [The-ring-io/flutter_phoenix#20]
I have tried what it says in the readme and it doesn't work.
Not that I did it wrong, I have tried it several times and the steps to follow are not very difficult, but for some reason this does not work...

This is my main.dart:

```
Future<void> main() async {
  runApp(Phoenix(child: const MyApp()));
}

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return ResponsiveSizer(
      builder: (context, orientation, screenType) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'What we game?',
          initialRoute: '/',
          routes: router,
        );
      },
    );
  }
}
```

And here is my button where I call the rebirth function:

```
class BotonSelectorTema extends StatelessWidget {
  final Color color;
  final String theme;

  const BotonSelectorTema({
    Key? key,
    required this.color,
    required this.theme,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _prefs = PreferenciasUsuario();
    return GestureDetector(
      onTap: () {
        _prefs.colorTheme = theme;
        Phoenix.rebirth(context);
      },
      child: Container(
        height: 4.h,
        width: 8.w,
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(5),
        ),
      ),
    );
  }
}
```

**Comment by Nandan-Wewhare** [comment]
Any updates on this?

**Comment by milanobrenovic** [comment]
+1, this plugin does not work for me either. Nothing happens when i call the rebirth() method, my app doesnt rebuild.

**Comment by hekhy** [comment]
I'm still the same and it doesn't work for me, it seems that the owner of the package left it abandoned.

**Comment by HannesGitH** [comment]
the problem most probably is that you call the rebirth with a different context then the one used to create the phoenix (see #18 )

an idea would be to expose the context and use that in the rebirth call

**Comment by hekhy** [comment]
It is possible but even if it is true and without taking away your reason, it is something strange, since when I call rebirth() it is the main context of the application in MaterialApp which is the main context of the application and everything that goes after it should be redrawn . It is also the way it says that the package is used.

**Comment by BeiAduo** [comment]
me too

**Comment by DevQC** [comment]
如果使用了MaterialApp，不能设置 navigatorKey。
If materialapp is used, the navigator key cannot be set.

**Comment by Miiite** [comment]
If this issue is still a problem for someone, please re-open it with a reproduction project. The code provided initially is custom, with external dependencies and cannot be run as is.

**Comment by iamnabink** [comment]
Working fine in my project.. as remi says "With the runApp solution, one must know what that root widget is" . So, Identify your root widget
