### ISSUE TITLE
When will you update dependencies...??? and add pure null safety please

### ISSUE THREAD

**Issue by fisforfaheem** [The-ring-io/flutter_phoenix#22]
i cant use it please

**Comment by vishnuagbly** [comment]
What do you mean by pure null safety? do you mean support for flutter 3.0?

**Comment by fisforfaheem** [comment]
sorry for my bad English, I meant flutter 3.0.5



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/19/22,
01:43:58 AM

**Comment by Miiite** [comment]
Package version `1.1.0` and above are compiled using the Dart SDK `2.17.0` but previous versions were also working properly with flutter `3.0` and above, so if you encounter an issue, please open a new issue with more details as to what's not working.

**Comment by fisforfaheem** [comment]
I was working on my project it having issues, maybe because of the depedecies issues, no need to to do anything on you side, just use flutter pub upgrade and then republish to see what changes were added.

**Comment by fisforfaheem** [comment]
thanks for updating, i wil try to use this package again,
