### ISSUE TITLE
completely not work

### ISSUE THREAD

**Issue by Miedziaq** [The-ring-io/flutter_phoenix#23]
This rebirth() method makes nothing... app completely not refreshed and not restarted...

**Comment by ravilimbani2203** [comment]
@Miedziaq Any solution i find same issues

**Comment by Miedziaq** [comment]
nope - i resign from this "feature" no one works on android and ios for me

**Comment by Miiite** [comment]
@Miedziaq Have you looked at the example project ?
The `rebirth()` method works properly there, and also in one of our project at Dailyn, so it might be something related to your project.
If you can, submit a reproduction code sample.
